# Specifies base image and tag
FROM python:3.7.12
WORKDIR /root

# Installs additional packages
RUN pip install google-cloud-aiplatform
RUN pip install google-cloud-bigquery==2.34.2
RUN pip pandas
RUN pip numpy
RUN pip google.cloud
RUN pip datetime
RUN pip google.protobuf
RUN pip json
RUN pip timeit
RUN pip sys
RUN pip os


