name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install black
        pip install pytest
        pip install numpy
        pip install pandas
        pip install -U scikit-learn
        pip install pyspark

    - name: Lint with Black
      run: |
        black --check .
    
    - name: testfunctionality.py
      run: |
        cd data/tests
        pytest testfunctionality.py